name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: bash ./gradlew app:testDebugUnitTestCoverage --stacktrace
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: b7c6be65-08ea-46bc-bc2d-f909fb4d1e4d
          files: ${{ github.workspace }}/app/build/reports/jacoco/testProdDebugUnitTestCoverage/testProdDebugUnitTestCoverage.xml